// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7QNfEwyLb4u88jfmAdCoh0B0cKu3H2B8',
    appId: '1:314165892127:web:5413bd65ad535d4a8eb12a',
    messagingSenderId: '314165892127',
    projectId: 'shanjeeban-bea7f',
    authDomain: 'shanjeeban-bea7f.firebaseapp.com',
    storageBucket: 'shanjeeban-bea7f.appspot.com',
    measurementId: 'G-SH44JSDGZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqONPMnrQCcQ-9vKD_VJs4jtFryaFtis4',
    appId: '1:314165892127:android:8a40f4237d13f6308eb12a',
    messagingSenderId: '314165892127',
    projectId: 'shanjeeban-bea7f',
    storageBucket: 'shanjeeban-bea7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfmz3fQAF4hTX3X7VtFNUAtbx8mZ1ndrI',
    appId: '1:314165892127:ios:942dc6ed13621bf88eb12a',
    messagingSenderId: '314165892127',
    projectId: 'shanjeeban-bea7f',
    storageBucket: 'shanjeeban-bea7f.appspot.com',
    iosBundleId: 'com.example.shanjeeban000',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfmz3fQAF4hTX3X7VtFNUAtbx8mZ1ndrI',
    appId: '1:314165892127:ios:e4e01c30ffbfb0d38eb12a',
    messagingSenderId: '314165892127',
    projectId: 'shanjeeban-bea7f',
    storageBucket: 'shanjeeban-bea7f.appspot.com',
    iosBundleId: 'com.example.shanjeeban000.RunnerTests',
  );
}
